4.6.2 Pick and Which
```{r}
set.seed(2020)
A <- sample(50:80, 10, replace = T)
pick <- A > 60
whichMetTheCondition <- which(pick)

A[pick]
A[whichMetTheCondition]
```

```{r}
grades <- c(51,70,79,78,67,74,80)
pick <- grades > 70
whichIs70plus <- which(pick)
grades[pick]
```

```{r}
grades <- c(51,70,79,78,67,74,80)
gender <- c('female','female','male','male','female','male','male')

pick <- grades > 70
gender[pick]
```

```{r}
dataSet1 <- 
  data.frame(
    school_id = c("001", "002", "003", "004"),
    course1_grade=c(55, 83, 92, 73),
    course2_grade=c(50, 88, 72, 77)
  )

pick <- dataSet1$course1_grade >=80
dataSet1$course2_grade[pick]
```

```{r}
dataSet1 |> names()
dataSet1$school_id[pick]
dataSet1$course1_grade[pick]
dataSet1$course2_grade[pick]

dataSet1[pick, ] -> subsample1
View(subsample1)

subset(dataSet1, course1_grade >=80) -> subsample2
```

```{r}
pick <- c(F, T, NA, T)

c(1, 2, 3, 4)[pick]
```


4.6.3 Multiple conditions
```{r}
gender = c('Female','Male','Male', 'Female')
age = c(28,41,42,33)
residence = c('South','South','North', 'North')
color=c("yellow", "pink", "blue", "green")

pick_male <- gender == 'Male'
pick_south <- residence == 'south'
!pick_male
pick_male & pick_south
pick_male | pick_south
```

```{r}
pick <- list()
pick$male <- gender == "Male"
print(pick$male)
pick$south <- residence == "South"
print(pick$south)
# and
pick$male_south <- pick$male & pick$south
print(pick$male_south)
age[pick$male_south]
# or
pick$maleOsouth <- pick$male | pick$south
print(pick$maleOsouth)
age[pick$maleOsouth]
# xor
pick$maleXOsouth <- xor(pick$male, pick$south)
print(pick$maleXOsouth)
```

```{r}
color[pick$male]
color[pick$south]
color[pick$maleOsouth]
color[pick$maleXOsouth]

pick$maleXsouth <- 
  pick$male & !pick$south
color[pick$maleXsouth]

pick$XmaleXsouth <-
  !pick$male & !pick$south
color[pick$XmaleXsouth]
```

```{r}
!(! pick$male)
pick$male

!(pick$male & pick$south)
!pick$male | !pick$south

!(pick$male | pick$south)
!pick$male & !pick$south
```

```{r}
pick$male
any(pick$male)
all(pick$male)
```

```{r}
pick2 <- c(T, T, NA)
any(pick2)
all(pick2)

pick3 <- c(F, F, NA)
any(pick3)
all(pick3)
```
