4.5 Pipe Operator
```{r}
chr <- c('C','C','A','A','B','B','B','B','C')
table(chr)
table(as.factor(chr))
factor(
  chr, levels = c('C', 'B', 'A')
)
```

```{r}
newLevels <- {
  table(chr) -> tb_chr
  tb_chr
  
  sort(tb_chr, decreasing = T) -> sorted_tb_chr
  sorted_tb_chr
  
  names(sorted_tb_chr)
}

fct_chr <- factor(chr, levels=newLevels)
fct_chr
table(fct_chr)
```


4.5.1 |>
```{r}
f(x)
x |> f()

g(x, y)
x |> g(y)

g(f(x), y)
g(x |> f(x), y)
x |> f(x) |> g(y)

x |> f(x) |> g(y) |> h(z)
```

```{r}
newLevels <- {
  
  chr |> table() -> tb_chr
  #table(chr) -> tb_chr
  #tb_chr
  
  tb_chr |> sort( decreasing = T) -> sorted_tb_chr
  #sort(tb_chr, decreasing = T) -> sorted_tb_chr
  #sorted_tb_chr
  
  sorted_tb_chr |> names()
  #names(sorted_tb_chr)
} #same as

newLevels <- {
  chr |> 
  table() |> 
  sort(decreasing=T) |>
  names()
}
```


4.5.2 %<>% and %T>%
```{r}
library(magrittr)
```

```{r}
df <-
data.frame(
  types = c('C','C','C','A','C','A','A','B','B','B','B','C'),
  response = c(83,59,54,68,64,88,72,73,66,94,53,55)
)

df$types |> class()
df$types %<>% factor()
df$types |> class()
```

```{r}
df$type |>
  factor() |>
  table()

df$type |>
  factor() %T>%
    print() |>
  table()
```


4.6.1
Comparison
```{r}
c(2, 3, -1) > c(3, 3, 5)
c(2, 3, -1) >= c(3, 3, 5)

pick <- c(2, 3, -1) >= c(3, 3, 5)
c(2, 3, -1)[pick]
```

```{r}
income <- factor(
  c('20,001-30,000','20,001-30,000','less than 10,000','10,001-20,000','10,001-20,000','20,001-30,000','20,001-30,000','20,001-30,000'),
  levels=c("less than 10,000", "10,001-20,000", "20,001-30,000"),
  ordered = T)

income < "10,001-20,000"
income <= "10,001-20,000" 

pick <- income < "10,001-20,000"
income[pick]
which(pick)
income[which(pick)]
```

```{r}
birthdays <- 
  lubridate::ymd(
    c('2017-11-29','2001-11-07','2011-03-30','2014-03-26','2011-04-20','2014-06-11')
  )


birthdays |> class()
pick <- birthdays > lubridate::ymd("2002-12-31")

birthdays[pick]
```

```{r}
pick <- c(5, 10, -1) > 0
sum(pick)

pick <- c(5, NA, -1) > 0
pick
sum(pick)
sum(pick, na.rm = T)

pick |>
  na.omit() |>
  sum()
```

Equal and identical
```{r}
studentGradesInputFromTA <- 
  c(88, 52, 73)
studentGradesFromTeacherCalculation <-
  c(88, 51, 72)

studentGradesInputFromTA ==
  studentGradesFromTeacherCalculation
```

```{r}
whichIsTheSame <- 
  which(
    studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation
  )
print(whichIsTheSame)
```

```{r}
print(studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation)
print(!(studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation))

whichIsDifferent <- 
  which(
    !(studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation)
  )

print(whichIsDifferent)
```

```{r}
c("A", "B", "C") == c("B", "A", "C")
!(c("A", "B", "C") == c("B", "A", "C"))
c("A", "B", "C") != c("B", "A", "C")

list("John", 182, 35) == list("John", 182, 40) #NO
```

```{r}
studentGradesInputFromTA2 <- c(
  82, NA, 73
)
studentGradesInputFromTA2 ==
  studentGradesFromTeacherCalculation

studentGradesFromTeacherCalculation2 <- c(
  82, NA, 73
)
pick <- studentGradesInputFromTA2 == 
  studentGradesFromTeacherCalculation2

sum(pick, na.rm = T)
```

```{r}
identical(studentGradesInputFromTA2,
   studentGradesFromTeacherCalculation2)

is.numeric(studentGradesFromTeacherCalculation2)
is.na(studentGradesInputFromTA2)
anyNA(studentGradesInputFromTA2) 
```

Recycling
```{r}
c(2, 3, -1) > c(3, 3, 5)
income < "10,001-20,000"
birthdays > lubridate::ymd("2002-12-31")

birthdays > rep(lubridate::ymd("2002-12-31"), 6)
```

```{r}
long_vctr = c("A", "B", "C", "D")

short_vctr = c(1, 2)

short_vctr_recycles = 
  c(c(1, 2), c(1, 2))[1:4]
short_vctr_recycles

short_vctr2 = c(1, 2, 3)

short_vctr_recycles2 = 
  c(c(1, 2, 3), c(1, 2, 3))[1:4]
short_vctr_recycles2
```

```{r}
vc1 = c("Apr.", "May.")
vc2 = c("1", "1")
paste(vc1, vc2)
paste(c("Apr.", "May."), c("1", "1"))
paste(c("Apr.", "May."), "1")
```

```{r}
.years <- as.character(rep(1998:2021, each=2))
print(.years)
length(.years)
.monthdays <- c("01-01", "07-01")
.dates <- paste(.years, .monthdays, sep="-")
print(.dates)
```

One of them
```{r}
majors <- c('economics','law','economics','sociology','sociology','sociology','sociology','economics','statistics','law')

set_schoolSocialScience <- c("economics", "sociology", "social work")
pickSchoolSocialScience <-
  majors %in% set_schoolSocialScience

print(pickSchoolSocialScience)
which(pickSchoolSocialScience)
```

```{r}
"1995" != "1995 "
"economics" != "Economics"
"台灣" != "臺灣"
```
