4.3 Class conversion
```{r}
c(2, 5, 7) + 3
c("2", "5", "7") + 3
convert2numeric <- as.numeric(c("2", "5", "7")) 
convert2numeric + 3
class(convert2numeric)
```

```{r}
c(2, 5, 7) + 3
list(2, 5, 7) + 3
```

```{r}
mylist <- list(2, 5, 7)
mylist[[1]] <- mylist[[1]]+3
mylist[[2]] <- mylist[[2]]+3
mylist[[3]] <- mylist[[3]]+3
print(mylist)

unlist(mylist) + 3
```


4.2.1 Character, numeric, logical
```{r}
examples <- list()
examples$unlist$source1 <-
  list("A", "B", "C")
examples$unlist$result1 <- 
  unlist(examples$unlist$source1)

print(examples$unlist$source1)
print(examples$unlist$result1)

class(examples$unlist$source1)
class(examples$unlist$result1)
```

```{r}
examples$unlist$source2 <- 
  list(
    list("A", "B", list("C")),
    list("D"),
    "E"
  )
examples$unlist$result2 <- 
  unlist(
    examples$unlist$source2
  )

print(examples$unlist$source2)
print(examples$unlist$result2)
class(examples$unlist$source2)
class(examples$unlist$result2)
```

```{r}
examples$unlist$source3 <- list(5, 6, 7)
examples$unlist$result3 <-
  unlist(
    examples$unlist$source3
  )

class(examples$unlist$source3)
class(examples$unlist$result3)
```

```{r}
namedList <- list(name="John", spouse="Mary")

unlist(
  namedList
) -> unlist_namedList

unlist_namedList
```


4.3.2 atomic vector to list
```{r}
as.list(
  c("A", "B", "C")
)

as.list(
  c(name="John", spouse="Mary")
)
```


4.3.3 among atomic vectors
```{r}
lgl <- c(TRUE, FALSE)
num <- c(0.2, 3, 0)

as.character(lgl)
as.character(num)
as.character(num) + 3 # error
```

```{r}
tookRcourse <- c(TRUE, FALSE, TRUE, TRUE)
class(tookRcourse)
as.numeric(tookRcourse)
howManyTookR <- sum(
  as.numeric(tookRcourse)
)
print(howManyTookR)

howManyTookR <- sum(tookRcourse)
print(howManyTookR)

tookRcourse
which(tookRcourse)
```

```{r}
ming_guoDates <- c("1100822","1090723") 
# 民國100-8-22，民國109-7-23


westernDates <- 
  as.numeric(ming_guoDates) +
  19110000

westernDates 

lubridate::ymd(westernDates)
```

```{r}
print(num)
as.logical(num)
```

```{r}
wage <- c(3000, 2000, 0, 1000)
haveJob <- as.logical(wage)
haveJob

whoHasAJob <- which(haveJob)
whoHasAJob

wage[whoHasAJob]
wage[c(1, 3)]
wage[c(3, 1)]
wage[c(T, F, F, T)]
```

```{r}
fct <- factor(
  c('參','貮','貮','貮','壹','貮','參','貮','參','參'),
  levels=c('壹','貮','參')
  )

dt <- lubridate::ymd_hms(
  c('2012-08-25 19:36:00','2018-01-06 10:44:00','2010-03-08 00:56:00')
)

print(fct)
as.character(fct)

typeof(fct)
as.numeric(fct)
```

```{r}
c('參','貮','貮','貮','壹','貮','參','貮','參','參')
persians <- factor( 
  c('۶','۹','۸','۹','۶','۸','۸','۵','۹','۹'),
  levels = c("۵", "۶", "۷", "۸", "۹")
  )
as.numeric(persians)
```

```{r}
print(dt)
as.character(dt)

typeof(dt)
as.numeric(dt)

dt
dt + 30
dt + 60*60
```

```{r}
x0 <- 1595950405
lubridate::as_datetime(x0)
```

```{r}
location_history <- jsonlite::fromJSON("https://www.dropbox.com/s/db2vt4w9u2w7onx/Location%20History.json?dl=1")

print(location_history$locations$timestampMs)
location_history$locations$timestampMs/(10**3)
class(location_history$locations$timestampMs)
```

```{r}
timeStampMs_as.numeric <- 
  as.numeric(
    location_history$locations$timestampMs
  )
timeStamp_inSecondUnit <-
  timeStampMs_as.numeric/(10**3)

timeStamp_dateTimeClass <-
  lubridate::as_datetime(
    timeStamp_inSecondUnit
  )
```


4.4 Programming Block
```{r}
answer <- {
  a = 3
  b = 2
  a + b
}
```

```{r}
location_history <- jsonlite::fromJSON("https://www.dropbox.com/s/db2vt4w9u2w7onx/Location%20History.json?dl=1")

class(location_history$locations$timestampMs)

timeStamp_dateTimeClass <- 
  {
     step1 <- as.numeric(
       location_history$locations$timestampMs)
    
     step2 <- step1/(10**3)
    
    lubridate::as_datetime(step2)
  }
```
