EX 4.5
```{r}
participations <- 
list('session 3',c("session 1", "session 2", "session 3"),'session 3',c("session 2", "session 1"),c("session 3", "session 1"),c("session 3", "session 2", "session 1"),'session 2','session 1',c("session 2", "session 1", "session 3"),c("session 3", "session 1", "session 2"))

participations[[1]] 
participations[[2]]
participations_result <- unlist(participations)
table(participations_result)
```

EX4.6
```{r}
numbers <- factor(
  c('參','貮','貮','貮','壹','貮','參','貮','參','參'),
  levels = c('壹','貮','參')
)

sum(as.numeric(numbers))
```

EX4.7
```{r}
persians_source <- factor(
  c('۶','۹','۸','۹','۶','۸','۸','۵','۹','۹'),
  levels = c("۵", "۶", "۷", "۸", "۹")
)

persians_result <- as.numeric(persians_source) + 4
as.numeric(persians_result)

sum(persians_result)

# another solvation
number5to9 <- c(5, 6, 7, 8, 9)
as.numeric(persians_source)
number5to9[as.numeric(persians_source)]
sum(number5to9[as.numeric(persians_source)])
```

EX4.8
```{r}
letter_grades <- c("C", "B-", "B", "B+", "A-", "A", "A+")
numeric_grades <- c(2, 2.5, 3, 3.5, 4, 4.5, 5)
studentGrades <- c('B','A','A+','B+','A-','B','B-','B','A+','B+','C','B-','B-','B','C','C','B+','B','B+','B')

studentLetterGrades <- {
  step1 <- 
    factor(
      studentGrades,
      levels = letter_grades
  )
  

  step2 <- numeric_grades[as.numeric(step1)]
}

```

EX4.9
```{r}
johnDoe <- list()
johnDoe$source[[1]] <- "https://www.moj.gov.tw/2204/2771/2773/76135/post"
johnDoe$source[[2]] <- "https://docs.google.com/spreadsheets/d/1g2AMop133lCAsmdPhsH3lA-tjiY5fkGIqXqwdknwEVk/edit#gid=640486514"
googlesheets4::read_sheet(
  johnDoe$source[[2]]
) -> johnDoe$data

johnDoe$data |> View()
yearPick <- johnDoe$data[["發現年"]] >= 101
yearPick |>
  na.omit() |>
  sum()
```

EX4.10
```{r}
agePick <- johnDoe$data[["年齡範圍上限"]] == 0
agePick |>
  na.omit() |>
  sum()
```

EX4.11
```{r}
num_input <- 
  c(1,NA,NA,1,1,NA,1,1,1,NA,NA,1,NA,NA,NA,1,NA,1,NA,1,1,1,1,NA,NA,NA,NA,NA,NA,1)
chr_input <- 
  c('NA','1','1','1','NA','NA','1','1','1','1','NA','1','NA','1','1','1','NA','NA','NA','1','NA','NA','NA','NA','NA','1','1','NA','NA','NA')

# 1.
num_input |> 
  is.na() |> which()

# 2.
(chr_input == 'NA') |> which()

```

EX4.12
```{r}
drug <- list()
drug$source[[1]] <- 
  "https://docs.google.com/spreadsheets/d/17ID43N3zeXqCvbUrc_MbpgE6dH7BjLm8BHv8DUcpZZ4/edit?usp=sharing"
drug$data <- 
  googlesheets4::read_sheet(
    drug$source[[1]]
  )

drug$data |> View()

drugSet <- c('安非他命','甲基安非他命','二甲氧基安非他命(DMA)','左旋甲基安非他命','3,4-亞甲基雙氧安非他命(MDA)')

# 1.
drugPick <- drug$data[["kind"]] == "安非他命"
drugPick |>
  na.omit() |>
  sum()

# 2.
drugSetPick <- drug$data[["kind"]] %in% drugSet
drugSetPick |>
  na.omit() |>
  sum()
```



