---
title: "study_remove"
output: html_notebook
---
```{r}
example2 <- c("John", "Mary", "Bill", person4="Jack")
```

```{r}
example2 <- example2[c(1, 2, 3)] 
```

```{r}
c(1, 2, 3)
1:3
example2 <- example2[1:3] #equal example2[c(1, 2, 3)] 
example2
```

```{r}
1:3 # the same as
seq(from = 1, to = 3, by = 1)

seq(from=3, to=11, by=4) # from 3 to 11 increase by 4
```

```{r}
seq(from=3, to=11, length.out=3) # divide interval [3, 11] into 10 equal length cuts
seq(from=3, to=11, length.out=5)
seq(from=7, to=15, length.out=3)
```

```{r}
example3 <- c("John", "Mary", "Bill", person4="Jack")

example3[c(1, 2, 3)]
example3[-c(4)]
example3[-c(1, 4)]
example3[-(1:4)] #same as example3[-c(1, 4)]
                # not example3[-1:4] 
```

```{r}
example6 <- c("John", "Mary", "Bill", person4="Jack")
example6[1:3]
example6[-c(4)]

```

```{r}
JohnsFamily <-
  list(
    name = "John", 
    age = 35,
    spouse = list(
      name = "Mary", 
      age = 32),
    children = list(
      list(
        name = "Bill", 
        age = 5),
      list(
        name = "Jane", 
        age = 3)
    )
  )
JohnsFamilyCopy5 <- JohnsFamilyCopy6 <- JohnsFamilyCopy7 <- JohnsFamilyCopy8 <-  JohnsFamily
```

```{r}
JohnsFamilyCopy5 <- 
  JohnsFamilyCopy5[-c(3)]
```
```{r}
JohnsFamilyCopy6$spouse <- NULL
JohnsFamilyCopy7[c(3, 4)] <- NULL
```


