4.2.3 Date/Time
```{r}
install.packages("lubridate")
```

```{r}
lubridate::ymd(c("2021/10/30", "2021-10-30", "2021 October 30", "2021 Oct. 30"))
lubridate::ydm(c("2021/30/10", "2021-30-10", "2021 30 October", "2021 30 Oct."))
lubridate::mdy(c("10/30/2021", "10-30-2021", "October 30, 2021", "Oct. 30, 2021"))
lubridate::dmy(c("30/10/2021", "30-10-2021", "30 October, 2021", "30 Oct., 2021"))
```

```{r}
dayInfo <- list()
dayInfo$ymd <- c("2021/10/30", "2021-10-30", "2021 October 30", "2021 Oct. 30")

class(dayInfo$ymd)
```

```{r}
lubridate::ymd(dayInfo$ymd) -> dayInfo$ymd_parsed
class(dayInfo$ymd_parsed)
```

```{r}
commonClasses <- list()
commonClasses$character <- c("John", "Mary", "Bill")
commonClasses$numeric <- c(2.3, 4, 7)
commonClasses$logical <- c(TRUE, T, F, FALSE)
```

```{r}
commonClasses$date <- lubridate::ymd(c("2021/10/30", "2021-10-30", "2021 October 30", "2021 Oct. 30"))
class(commonClasses$date)
```

```{r}
lubridate::ymd_hms(
      c("2021/10/30 13:22:52", "2021-10-31 1:22:52PM"),
      tz="Asia/Taipei"
   ) -> dateTime_taipei

dateTime_london <- 
  lubridate::mdy_hms(
    c("October 30, 2021, 23:10", "Oct. 30, 2021 11:10PM"),
    tz="Europe/London")
dateTime_london
```

```{r}
commonClasses$date_time <- c(
  dateTime_taipei,
  dateTime_london
)
commonClasses$date_time
class(commonClasses$date_time)
```

```{r}
dateTime_london_atTaipei <-
  lubridate::with_tz(
    dateTime_london,
    tz="Asia/Taipei"
  )
class(dateTime_london)
dateTime_london
dateTime_london_atTaipei
```

EX4.2
```{r}
subsidiaries <- list()
subsidiaries$boston <- c("2020 Oct. 13 15:00:00", "2019 Apr. 10 09:30:00")
subsidiaries$mykonos <- c("14 Jan., 2021 03:27:00", "8 Aug., 2020 11:20:00")

dateTime_boston <- 
  lubridate::ymd_hms(
    subsidiaries$boston,
    tz="America/New_York")
dateTime_mykonos <- 
  lubridate::dmy_hms(
    subsidiaries$mykonos,
    tz="Europe/Athens")
dateTime_boston_atIndia <-
  lubridate::with_tz(
    dateTime_boston,
    tz="Asia/Calcutta"
  )
dateTime_mykonos_atIndia <-
  lubridate::with_tz(
    dateTime_mykonos,
    tz="Asia/Calcutta"
  )

subsidiaries_dayTime <- list()
subsidiaries_dayTime <- c(
  dateTime_boston_atIndia,
  dateTime_mykonos_atIndia
)
subsidiaries_dayTime
```


4.2.4 Data frame
```{r}
survey_fbf <-
  list(
    age=c(54, 32, 28, 20),
    gender=c("male", "female", "female", "male"),
    residence=c("north", "south", "east", "east"),
    income=c(100, 25, NA, 77)
  )
```

```{r}
survey_df <-
  data.frame(
    survey_fbf
  )

class(survey_fbf)
class(survey_df)
```

```{r}
commonClasses <- list()
commonClasses$data_frame <- survey_df
```

```{r}
survey_fbf2 <-
  list(
    age=list(54, 32, 28, 20),
    gender=list("male", "female", "female", "male"),
    residence=list("north", "south", "east", "east"),
    income=list(100, 25, NA, 77)
  )


df_survey_fbf2 <- 
  list2DF(survey_fbf2)
df_survey_fbf2
```

```{r}
survey_fbf$age
df_survey_fbf <- data.frame(survey_fbf)
df_survey_fbf
df_survey_fbf$age

survey_fbf2$age
df_survey_fbf2$age

df_survey_fbf
df_survey_fbf2
```

```{r}
commonClasses$data_frame
commonClasses$data_frame[2, "age"]
commonClasses$data_frame[2, 1]
commonClasses$data_frame[c(1,4), c("income","age")]
commonClasses$data_frame[c(1,4), c(4, 1)]
```

```{r}
commonClasses$data_frame[, -c(2)]
commonClasses$data_frame[2, c( "age","income")] <- data.frame(31, 22)
commonClasses$data_frame[c(1,2), c("age", "income")] <- data.frame(
  age=c(10, 15),
  income=c(10, 15)
)

commonClasses$data_frame[, "isStudent"] <- data.frame(isStudent=c(T, T, F, T))
commonClasses$data_frame
```

EX4.3
```{r}
dfExercise <- list()
dataSet1 <- list(
  name=c("John", "Mary", "Ben"),
  age=c(33, 45, NA)
)
dfExercise$data1 <-
  data.frame(
    dataSet1
  )
dataSet1$children <- list(
  list(list(name = "Jane", age = 2), NA),
  list(list(name = "Bill", age = 3),
       list(name = "Ken", age = 0)),
  list(list(name = "William", age = 10), NA)
)

dataSet1$children[[1]][[1]]
dataSet1$children[[2]][[1]]
dataSet1$children[[2]][[2]]
dataSet1$children[[3]][[1]]

dfExercise$data2 <- data.frame(dataSet1$children)
```



4.2.5 Matrix
```{r}
commonClasses$matrix <- matrix(
  c(2, 11, -1, 3, 4, -5), nrow=2, 
  byrow = T
)
class(commonClasses$matrix)
```

```{r}
matrix_nonAtomic <- matrix(
  list(
    32, "John", 
    33, "Jane", 
    34, "Ben"
    ), nrow=2
)
matrix_nonAtomic
```


