EX5.1
```{r}
# Observation by observation
concerts_obo <-
  jsonlite::fromJSON("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=17", simplifyDataFrame = F)

View(concerts_obo)

# 1.
length(concerts_obo[[5]]$showInfo)

# 2.
analysis <- list()
analysis$number_of_showInfo <- list()

analysis$number_of_showInfo[[.x]] <-length(concerts_obo[[5]]$showInfo)# .x-pattern

# 3.
analysis <- list()
analysis$number_of_shows <- vector("list", length(concerts_obo))

for(.x in seq_along(concerts_obo)){
  analysis$number_of_shows[[.x]] <-length(concerts_obo[[.x]]$showInfo)
}

# 4.
data4 <- list()
data4$title <- vector("list", length(concerts_obo))
data4$date <- vector("list", length(concerts_obo))
data4$location <- vector("list", length(concerts_obo))
data4$locationName <- vector("list", length(concerts_obo))

for(.x in seq_along(concerts_obo)){
  data4$title[[.x]] <- (concerts_obo[[.x]]$title)
  data4$date[[.x]] <-
    (concerts_obo[[.x]]$showInfo[[1]]$time)
  data4$location[[.x]] <-
    (concerts_obo[[.x]]$showInfo[[1]]$location)
  data4$locationName[[.x]] <-
    (concerts_obo[[.x]]$showInfo[[1]]$locationName)
}

data4$date <- lubridate::ymd_hms(
      data4$date, tz="Asia/Taipei"
   )

data4_frame <- list2DF(data4)
```

EX5.2
```{r}
drug <- list()
drug$source[[1]] <- 
  "https://docs.google.com/spreadsheets/d/17ID43N3zeXqCvbUrc_MbpgE6dH7BjLm8BHv8DUcpZZ4/edit?usp=sharing"
drug$data <- 
  googlesheets4::read_sheet(
    drug$source[[1]]
  )

View(drug$data)

# 1.
split(drug$data, drug$data$kind) -> grouped_drugKind
grouped_drugKind$毒品品項 <- NULL
View(grouped_drugKind)

group_meanWeight <- vector("numeric",
                           length(grouped_drugKind))
for(.x in seq_along(grouped_drugKind)){
  group_meanWeight[[.x]] <- mean(as.numeric(grouped_drugKind[[.x]]$weight_g))
}
group_meanWeight

# 2.
pickDate <- drug$data$oc_dt
pickDate <- as.numeric(pickDate[-c(1)]) + 19110000
View(pickDate)
drug$data$date <- vector("numeric",
                           length(drug$data$oc_dt))
for(.x in seq_along(pickDate)){
  drug$data$date[[.x+1]] <- pickDate[[.x]]
}
drug$data$date <- lubridate::ymd(drug$data$date)
drug$data$date[[1]] <- NA

# 3.
pick3 <- grouped_drugKind$安非他命
pick3$oc_dt <- lubridate::ymd(as.numeric(pick3$oc_dt) +19110000)

split(pick3, lubridate::year(pick3$oc_dt)) -> pick3
pick3_sum <- vector("numeric",
                           length(pick3))
for(.x in seq_along(pick3)){
  pick3_sum[[.x]] <- length(pick3[[.x]]$no)
  pick3[[.x]] <- pick3_sum[[.x]]
}
table(pick3)
```

EX5.3
```{r}
a=1; b=-3; c=0; d=1
# 1
pick5_3_1=list(
  q_star=(a-c)/(d-b), 
  p_star=a+b*q_star
)
pick5_3_1
```

```{r}
a=1; b=-3; c=0; d=1
equilibrium1 <- solve_equilibrium()
print(equilibrium1)
a=2; b=-3; c=0; d=1
equilibrium2 <- solve_equilibrium()
print(equilibrium2)
a=1; b=-3; c=0; d=1.5
equilibrium3 <- solve_equilibrium()
print(equilibrium3)
```

```{r, echo=FALSE}
solve_equilibrium <- function(){
  q_star <- (a-c)/(d-b)
  p_star <- a+b*q_star
  equilibrium <- list("q_star"=q_star, "p_star"=p_star)
  equilibrium
}
```
