EX4.1
```{r}
customerExperience <- c('very happy','very happy','satisfied','satisfied','satisfied','very happy','bad','bad','satisfied','satisfied','bad','happy','happy','very happy','happy','happy','satisfied','very happy','very happy','satisfied','satisfied','very happy','satisfied','bad','very happy','very bad','very happy','bad','bad','very bad')

customerExperience_fct <- factor(customerExperience)
class(customerExperience_fct)
table(customerExperience_fct)

customerExperience_fct_levelsSetup <- factor(customerExperience, 
         levels = c('very bad', 
                    'bad','satisfied','happy','very happy')
      )
class(customerExperience_fct_levelsSetup)

customerExperience_fct_levelsSetup_ordered <-
   factor(customerExperience_fct_levelsSetup, 
   levels = c('very bad','bad','satisfied','happy','very happy'),
   ordered = T
      )

rev(c('very bad','bad','satisfied','happy','very happy'))


table(customerExperience_fct_levelsSetup_ordered)
class(customerExperience_fct_levelsSetup_ordered)

customerExperience_fct_levelsSetup_ordered[[1]]
customerExperience_fct_levelsSetup_ordered[[1]] < 'happy'
customerExperience_fct_levelsSetup_ordered[[1]] > 'happy'
```

EX4.2
```{r}
subsidiaries <- list()
subsidiaries$boston <- c("2020 Oct. 13 15:00:00", "2019 Apr. 10 09:30:00")
subsidiaries$mykonos <- c("14 Jan., 2021 03:27:00", "8 Aug., 2020 11:20:00")

dateTime_boston <- 
  lubridate::ymd_hms(
    subsidiaries$boston,
    tz="America/New_York")
dateTime_mykonos <- 
  lubridate::dmy_hms(
    subsidiaries$mykonos,
    tz="Europe/Athens")
dateTime_boston_atIndia <-
  lubridate::with_tz(
    dateTime_boston,
    tz="Asia/Calcutta"
  )
dateTime_mykonos_atIndia <-
  lubridate::with_tz(
    dateTime_mykonos,
    tz="Asia/Calcutta"
  )

subsidiaries_dayTime <- list()
subsidiaries_dayTime <- c(
  dateTime_boston_atIndia,
  dateTime_mykonos_atIndia
)
subsidiaries_dayTime
```

EX4.3
```{r}
dfExercise <- list()
dataSet1 <- list(
  name=c("John", "Mary", "Ben"),
  age=c(33, 45, NA)
)
dfExercise$data1 <-
  data.frame(
    dataSet1
  )
dataSet1$children <- list(
  list(list(name = "Jane", age = 2), NA),
  list(list(name = "Bill", age = 3),
       list(name = "Ken", age = 0)),
  list(list(name = "William", age = 10), NA)
)

dataSet1$children[[1]][[1]]
dataSet1$children[[2]][[1]]
dataSet1$children[[2]][[2]]
dataSet1$children[[3]][[1]]

dfExercise$data2 <- data.frame(dataSet1$children)
View(dfExercise$data2)
```

EX 4.5
```{r}
participations <- list(
  'session 3',
  c("session 1", "session 2", "session 3"),
  'session 3',
  c("session 2", "session 1"),
  c("session 3", "session 1"),
  c("session 3", "session 2", "session 1"),
  'session 2',
  'session 1',
  c("session 2", "session 1", "session 3"),
  c("session 3", "session 1", "session 2")
  )

participations[[1]] 
participations[[2]]
participations_result <- unlist(participations)
table(participations_result)
```

EX4.6
```{r}
numbers <- factor(
  c('參','貮','貮','貮','壹','貮','參','貮','參','參'),
  levels = c('壹','貮','參')
)

sum(as.numeric(numbers))
```

EX4.7
```{r}
persians_source <- factor(
  c('۶','۹','۸','۹','۶','۸','۸','۵','۹','۹'),
  levels = c("۵", "۶", "۷", "۸", "۹")
)

persians_result <- as.numeric(persians_source) + 4
as.numeric(persians_result)

sum(persians_result)

# another solvation
number5to9 <- c(5, 6, 7, 8, 9)
as.numeric(persians_source)
number5to9[as.numeric(persians_source)]
sum(number5to9[as.numeric(persians_source)])
```

EX4.8
```{r}
letter_grades <- c("C", "B-", "B", "B+", "A-", "A", "A+")
numeric_grades <- c(2, 2.5, 3, 3.5, 4, 4.5, 5)
studentGrades <- c('B','A','A+','B+','A-','B','B-','B','A+','B+','C','B-','B-','B','C','C','B+','B','B+','B')

studentLetterGrades <- {
  step1 <- 
    factor(
      studentGrades,
      levels = letter_grades
  )
  

  step2 <- numeric_grades[as.numeric(step1)]
}

```

EX4.9
```{r}
johnDoe <- list()
johnDoe$source[[1]] <- "https://www.moj.gov.tw/2204/2771/2773/76135/post"
johnDoe$source[[2]] <- "https://docs.google.com/spreadsheets/d/1g2AMop133lCAsmdPhsH3lA-tjiY5fkGIqXqwdknwEVk/edit#gid=640486514"
googlesheets4::read_sheet(
  johnDoe$source[[2]]
) -> johnDoe$data

johnDoe$data |> View()
yearPick <- johnDoe$data[["發現年"]] > 101
yearPick |>
  na.omit() |>
  sum()
```

EX4.10
```{r}
agePick <- johnDoe$data[["年齡範圍上限"]] == 0
agePick |>
  na.omit() |>
  sum()
```

EX4.11
```{r}
num_input <- 
  c(1,NA,NA,1,1,NA,1,1,1,NA,NA,1,NA,NA,NA,1,NA,1,NA,1,1,1,1,NA,NA,NA,NA,NA,NA,1)
chr_input <- 
  c('NA','1','1','1','NA','NA','1','1','1','1','NA','1','NA','1','1','1','NA','NA','NA','1','NA','NA','NA','NA','NA','1','1','NA','NA','NA')

# 1.
num_input |> 
  is.na() |> which()

# 2.
(chr_input == 'NA') |> which()

```

EX4.12
```{r}
drug <- list()
drug$source[[1]] <- 
  "https://docs.google.com/spreadsheets/d/17ID43N3zeXqCvbUrc_MbpgE6dH7BjLm8BHv8DUcpZZ4/edit?usp=sharing"
drug$data <- 
  googlesheets4::read_sheet(
    drug$source[[1]]
  )

drug$data |> View()

drugSet <- c('安非他命','甲基安非他命','二甲氧基安非他命(DMA)','左旋甲基安非他命','3,4-亞甲基雙氧安非他命(MDA)')

# 1.
drugPick <- drug$data[["kind"]] == "安非他命"
drugPick |>
  na.omit() |>
  sum()

# 2.
drugSetPick <- drug$data[["kind"]] %in% drugSet
drugSetPick |>
  na.omit() |>
  sum()
```

EX4.13
```{r}
johnDoe <- list()
johnDoe$source[[1]] <- "https://www.moj.gov.tw/2204/2771/2773/76135/post"
johnDoe$source[[2]] <- "https://docs.google.com/spreadsheets/d/1g2AMop133lCAsmdPhsH3lA-tjiY5fkGIqXqwdknwEVk/edit#gid=640486514"
googlesheets4::read_sheet(
  johnDoe$source[[2]]
) -> johnDoe$data
johnDoe$data |> View()

# 1.
pick1 <- !is.na(johnDoe$data$通報機關名稱)
subsample1 <- johnDoe$data[pick1, ]
View(subsample)

# 2.
pick2 <- johnDoe$data$通報機關名稱 == '海巡隊'
johnDoe$data$死亡方式描述[pick2]
table(johnDoe$data$死亡方式描述[pick2])

# 3.
pick3 <- (johnDoe$data$死亡方式描述 == '不詳'
         | johnDoe$data$死亡方式描述 == '他殺')
johnDoe$data$發現縣市[pick3]
table(johnDoe$data$發現縣市[pick3])
```

EX4.14
```{r}
fraud <- list()
fraud$source[[1]] <- "https://data.gov.tw/dataset/78432"
fraud$source[[2]] <- "https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=7F6BE616-8CE6-449E-8620-5F627C22AA0D"
fraud$data <- readr::read_csv(fraud$source[[2]])
fraud$data |> View()

# 1.
fraudDate <-lubridate::ymd(fraud$data$通報日期)
any(is.na(fraudDate))

# 2.
fraud_pick2 <- fraudDate >= lubridate::ymd('2019-01-01')
sum(fraud_pick2, na.rm = T)

# 3.
fraud_pick3 <- (fraudDate >= lubridate::ymd('2019-01-01')
             & fraudDate < lubridate::ymd('2021-01-01')
              )
sum(fraud_pick3, na.rm = T)
```

EX4.15
```{r}
johnDoe <- list()
johnDoe$source[[1]] <- "https://www.moj.gov.tw/2204/2771/2773/76135/post"
johnDoe$source[[2]] <- "https://docs.google.com/spreadsheets/d/1g2AMop133lCAsmdPhsH3lA-tjiY5fkGIqXqwdknwEVk/edit?usp=sharing"
googlesheets4::read_sheet(
  johnDoe$source[[2]]
) -> johnDoe$data

johnDoe$data |> View()

# 1.
pick_john <- 
  stringr::str_detect(
    johnDoe$data$通報機關名稱, "海巡隊"
    )
subsample_john <- johnDoe$data[which(pick_john), ]
View(subsample_john)

# 2.
table(johnDoe$data$通報機關名稱[which(pick_john)])
```

EX4.16
```{r}
johnDoe$data |> View()

# 1.
df_dates =
  data.frame(
    year = johnDoe$data$發現年 + 1911,
    month = johnDoe$data$發現月,
    day = johnDoe$data$發現日
  )
chr_dates <- paste(df_dates$year, df_dates$month, df_dates$day)
johnDoe$data$發現日期 <- lubridate::ymd(chr_dates)

# 2.
sum(is.na(johnDoe$data$發現日期))

# 3.
table(johnDoe$data$發現月)
pick_month <- which.max(table(johnDoe$data$發現月))
table(johnDoe$data$發現月)[pick_month]
```

EX4.17
```{r}
johnDoe$data |> View()

# 1.
season = ""
pick_spring = johnDoe$data$發現月 %in% c(3, 4, 5)
season[pick_spring] = "spring"
pick_summer = johnDoe$data$發現月 %in% c(6, 7, 8)
season[pick_summer] = "summer"
pick_fall = johnDoe$data$發現月 %in% c(9, 10, 11)
season[pick_fall] = "fall"
pick_winter = johnDoe$data$發現月 %in% c(1, 2, 12)
season[pick_winter] = "winter"

johnDoe$data$發現季節 <- factor(
  season, 
  levels=c("spring", "summer", "fall", "winter")
)
  
# 2.
table(johnDoe$data$發現季節)
```

EX4.18
```{r}
majors <- c('economics','economics',NA,'economics','economics','economics','economics','statistics','law','economics','law')

length(majors)
table(majors)
majors |> unique()
majors |> table(useNA = "always")
```

EX4.19
```{r}
wdi <- list()
wdi$source[[1]] <- "https://databank.worldbank.org/source/world-development-indicators#"
wdi$source[[2]] <- "https://docs.google.com/spreadsheets/d/1XHxjE3DIIdvNL-kbLR_bktxiHxmk23S6lUmn89WEedM/edit?usp=sharing"
wdi$meta <- "https://docs.google.com/spreadsheets/d/1C8b-liC8Gl9Kmkexb5uq1_TUIE3lYOt4PutPlOne80g/edit?usp=sharing"
wdi$data <- googlesheets4::read_sheet(
  wdi$source[[2]]
)

View(wdi$data)

# 1.
wdiYear <- split(wdi$data,wdi$data$year)
wdiYear2000 <- wdiYear$`2000`
View(wdiYear2000)
length(wdiYear2000$year)

# 2.
iso2c_nonCountry <- c('ZH','ZI','1A','S3','B8','V2','Z4','4E','T4','XC','Z7','7E','T7','EU','F1','XE','XD','XF','ZT','XH','XI','XG','V3','ZJ','XJ','T2','XL','XO','XM','XN','ZQ','XQ','T3','XP','XU','XY','OE','S4','S2','V4','V1','S1','8S','T5','ZG','ZF','T6','XT','1W')

subsampleCountry2000 <- subset(
  wdiYear2000, !(wdiYear2000$iso2c %in% iso2c_nonCountry)
  )
View(subsampleCountry2000)

# 3.
length(subsampleCountry2000$country)
length(unique(subsampleCountry2000$country))

# 4.
browseURL(wdi$meta)

observations <- list()
summary <- subsampleCountry2000$EG.USE.PCAP.KG.OE
View(summary)

naSummary <- sum(is.na(summary))
rangeSummary <- range(summary, na.rm=T)
medianSummary <- median(summary, na.rm=T)
meanSummary <- mean(summary, na.rm=T)

allSummary <- list(
    observations = length(summary),
    missing = naSummary,
    range = list(rangeSummary),
    median= medianSummary,
    mean= meanSummary
  )

View(allSummary)
summary_df <- list2DF(allSummary)
```

