4.1 Class
```{r}
typeof(c("John", "Mary"))
typeof(c(2, 3.1412))
typeof(c(TRUE, TRUE, F))

class(c("John", "Mary"))
class(c(2, 3.1412))
class(c(TRUE, TRUE, F))

```

```{r}
dateTimeInfo <- "2021-01-01 12:03:33"
typeof(dateTimeInfo)
class(dateTimeInfo)
```

```{r}
dateTimeInfo + 20
"2021-01-01 12:03:33" + "20 seconds"
```

```{r}
install.packages("lubridate")
```

```{r}
dateTimeInfo2 <- lubridate::ymd_hms("2021-01-01 12:03:33")
dateTimeInfo2
typeof(dateTimeInfo2)
class(dateTimeInfo2)

dateTimeInfo2 + lubridate::seconds(20)

class("2021-01-01 12:03:33")
class(lubridate::ymd_hms("2021-01-01 12:03:33"))
```


4.2 Common classes of object value
```{r}
commonClasses <- list()

commonClasses$character <- c("John", "Mary", "Bill")
commonClasses$numeric <- c(2.3, 4, 7)
commonClasses$logical <- c(TRUE, T, F, FALSE)
```

```{r}
class(commonClasses$character)
class(commonClasses$numeric)
class(commonClasses$logical)
```

```{r}
bloodTypes <- c("AB", "AB", "A", "B", "A", "A", "B", "O", "O", "AB")
```

```{r}
bloodTypes_fct <- factor(bloodTypes)
class(bloodTypes)
class(bloodTypes_fct)
```

```{r}
table(bloodTypes)
table(bloodTypes_fct)
levels(bloodTypes)
levels(bloodTypes_fct)
```

```{r}
bloodTypes_fct_levelsSetup <- 
  factor(bloodTypes, levels=c("A", "B", "O", "AB"))

class(bloodTypes_fct_levelsSetup)
table(bloodTypes_fct_levelsSetup)
levels(bloodTypes_fct_levelsSetup)
```

```{r}
household_income <- c("low income", "low income", "middle income", "low income", "high income", "middle income", "high income", "high income", "middle income", "middle income")

household_income_fct <- factor(household_income)
levels(household_income_fct)
table(household_income_fct)
```

```{r}
household_income_fct_levelsSetup <-
  factor(household_income, levels = c("low income", "middle income", "high income"))
levels(household_income_fct_levelsSetup)

table(household_income_fct_levelsSetup)
```

```{r}
household_income_fct_levelsSetup[[1]]
household_income_fct_levelsSetup[[1]] > "low income"
household_income_fct_levelsSetup_ordered[[1]] > "low income"
```

```{r}
household_income_fct_levelsSetup_ordered <-
  factor(
    household_income, 
    levels = c("low income", "middle income", "high income"),
    ordered = T
    )

class(household_income_fct_levelsSetup_ordered)
```

```{r}
commonClasses$ordered_factor <- household_income_fct_levelsSetup_ordered
class(commonClasses$ordered_factor)
```

```{r}
commonClasses$factor <- bloodTypes_fct_levelsSetup
class(commonClasses$factor)
household_income_fct_levelsSetup_ordered[[2]]
household_income_fct_levelsSetup_ordered[[1]] < "low income"
household_income_fct_levelsSetup_ordered[[1]] < "middle income"
```

```{r}
household_income_fct_levelsSetup_ordered[[1]]
household_income_fct_levelsSetup_ordered[[1]] > "low income"

household_income_fct_levelsSetup_ordered[[1]]
household_income_fct_levelsSetup_ordered[[3]] > "low income"
```



EX4.1
```{r}
customerExperience <- c('very happy','very happy','satisfied','satisfied','satisfied','very happy','bad','bad','satisfied','satisfied','bad','happy','happy','very happy','happy','happy','satisfied','very happy','very happy','satisfied','satisfied','very happy','satisfied','bad','very happy','very bad','very happy','bad','bad','very bad')

customerExperience_fct <- factor(customerExperience)
class(customerExperience_fct)
table(customerExperience_fct)

customerExperience_fct_levelsSetup <- factor(customerExperience, 
         levels = c('very bad', 
                    'bad','satisfied','happy','very happy')
      )
class(customerExperience_fct_levelsSetup)

customerExperience_fct_levelsSetup_ordered <-
factor(customerExperience, 
       levels = c('very bad', 
            'bad','satisfied','happy','very happy'),
       ordered = T
      )
table(customerExperience_fct_levelsSetup_ordered)
class(customerExperience_fct_levelsSetup_ordered)
customerExperience_fct_levelsSetup_ordered[[7]]
customerExperience_fct_levelsSetup_ordered[[1]] 

```







