---
title: "practice"
output: html_notebook
---
```{r}
 install.packages('curl')

# Observation by observation
concerts_obo <-
  jsonlite::fromJSON("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=17", simplifyDataFrame = F)

# Feature by feature
concerts_fbf <-
  jsonlite::fromJSON("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=17", simplifyDataFrame = T)


View(concerts_fbf)

```

```{r}
ex <- concerts_obo

```


Exercise 3.2 

```{r}
concerts_sampled <- concerts_obo[c(3,5)] 

firstShowInfo <- concerts_obo[[2]][["showInfo"]][[1]][c("time","location")]

```

Exercise 3.3

```{r}
concerts_obo[[3]]$showInfo[[1]][c(1, 2)] <- list(time="2022/01/31 19:30:00", location="Taichung Opera House" )

```

Exercise 3.4

```{r}
JohnsFamilyCopy3 <- JohnsFamily
JohnsFamilyCopy3$children[3] <- "new born"

```

Exercise 3.5

```{r}

concerts_obo[[5]]$showInfo[[2]] <- list()
concerts_obo[[5]]$showInfo[[2]] <- concerts_obo[[5]]$showInfo[[1]]
concerts_obo[[5]]$showInfo[[2]][c(1, 8)] <- list(time="2021/12/20 10:00:00", endTime="2021/12/21 22:00:00")

```

Exercise 3.6

```{r}
concerts_obo <- concerts_obo[-c(2,5,7)]

```


